version: "3.9"
services:
 frontend:
   build:
     context: ./
     dockerfile: Dockerfile
   container_name: react-docker-demo
   restart: always
   ports:
     - 3000:3000
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost/api
   networks:
     - network
networks:
 network: